### PR TITLE
Add missing ax checking

### LINKED ISSUE #309: nightshade() requires explicit ax argument in 1.0.8
After upgrading to current master from 1.0.7, I ran into an error with the following code:
```python
from datetime import datetime
from mpl_toolkits.basemap import Basemap
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
                                                                                        
fig = Figure()                                                                          
axes = fig.add_subplot(111)                                                             
map = Basemap(projection='moll', lon_0=0, ax=axes)                                      
map.nightshade(datetime.now())                                                 
canvas = FigureCanvas(fig)                                                              
canvas.print_figure('test.png')                                                         
```
This results in
```python
Traceback (most recent call last):
  File "testbasemap.py", line 10, in <module>
    map.nightshade(datetime.now())
  File "/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 4668, in nightshade
    CS.collections,c = self._cliplimb(ax,CS.collections)
  File "/usr/local/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 1804, in _cliplimb
    if c not in ax.patches:
AttributeError: 'NoneType' object has no attribute 'patches'
```

This doesn't happen in 1.0.7.

The work-around is to use
```python
map.nightshade(datetime.now(), ax=axes)                                                 
```

but overall, this seems to be a regression bug of sorts.

### PR DESCRIPTION
**Pull request by WeatherGod**
closes #309. Also fixes a py2.6 compat issue I noticed along the way.

### CODE REVIEW

**Comment by WeatherGod** [comment]
uhm... where's my Travis testing?

**Comment by micahcochran** [comment]
> uhm... where's my Travis testing?

I was wondering the same thing.   You might close the PR and immediately reopen it.  [Travis looks operational.](https://www.traviscistatus.com/)
